apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - podinfo-source.yaml
  - podinfo-kustomization.yaml
  - nginx-kustomization.yaml
  #- postgres-helmrepo.yaml       
  #- postgres-helmrelease.yaml
  - cnpg-helmrepo.yaml
  - cnpg-helmrelease.yaml
  - cnpg-cluster.yaml
